SUPPORTED_PARAMETERS = {
    "page_format",
    "page_orientation",
    "top_margin",
    "bottom_margin",
    "left_margin",
    "right_margin",
    "header_distance",
    "footer_distance",
    "font_family",
    "font_size",
    "font_color",
    "bold",
    "italic",
    "alignment",
    "line_spacing",
    "first_line_indent",
    "left_indent",
    "right_indent",
    "space_before",
    "space_after",
    "keep_with_next",
    "keep_together",
    "page_break_before",
}


EXTRACTORS = [
    {
        "parameter": "font_size",
        "default_target": "main_text",
        "unit": "pt",
        "keywords": ["кегль", "размер шрифта", "размером", "кеглем"],
        "value_pattern": r"(\d+(?:[.,]\d+)?)\s*(?:пт|пункт)?",
        "operator": "equals",
        "value_type": "number",
    },
    {
        "parameter": "font_family",
        "default_target": "main_text",
        "unit": None,
        "keywords": ["гарнитура", "шрифт"],
        "value_pattern": r"(Times New Roman|Arial|Calibri|Aptos|Courier New|Cambria)",
        "operator": "equals",
        "value_type": "string",
    },
    {
        "parameter": "top_margin",
        "default_target": "page",
        "unit": "cm",
        "keywords": ["верхнее поле", "поле сверху", "верхнего поля"],
        "value_pattern": r"(\d+(?:[.,]\d+)?)\s*(см|мм)",
        "operator": "equals",
        "value_type": "length_cm",
    },
    {
        "parameter": "bottom_margin",
        "default_target": "page",
        "unit": "cm",
        "keywords": ["нижнее поле", "поле снизу", "нижнего поля"],
        "value_pattern": r"(\d+(?:[.,]\d+)?)\s*(см|мм)",
        "operator": "equals",
        "value_type": "length_cm",
    },
    {
        "parameter": "left_margin",
        "default_target": "page",
        "unit": "cm",
        "keywords": ["левое поле", "поле слева", "левого поля"],
        "value_pattern": r"(\d+(?:[.,]\d+)?)\s*(см|мм)",
        "operator": "equals",
        "value_type": "length_cm",
    },
    {
        "parameter": "right_margin",
        "default_target": "page",
        "unit": "cm",
        "keywords": ["правое поле", "поле справа", "правого поля"],
        "value_pattern": r"(\d+(?:[.,]\d+)?)\s*(см|мм)",
        "operator": "equals",
        "value_type": "length_cm",
    },
    {
        "parameter": "line_spacing",
        "default_target": "main_text",
        "unit": None,
        "keywords": ["интервал", "интерлиньяж", "межстрочный интервал"],
        "value_pattern": r"(полуторн\w*|одинарн\w*|1[.,]5|1(?:[.,]0)?)",
        "operator": "equals",
        "value_type": "mapped_number",
        "value_map": {
            "полуторный": 1.5,
            "полуторного": 1.5,
            "полуторным": 1.5,
            "одинарный": 1.0,
            "одинарного": 1.0,
            "одинарным": 1.0,
        },
    },
    {
        "parameter": "font_color",
        "default_target": "main_text",
        "unit": None,
        "keywords": ["цвет"],
        "value_pattern": r"(ч[её]рн\w*|черн\w*|000000)",
        "operator": "equals",
        "value_type": "mapped_string",
        "value_map": {
            "чёрный": "000000",
            "черный": "000000",
            "чёрного": "000000",
            "черного": "000000",
            "000000": "000000",
        },
    },
    {
        "parameter": "first_line_indent",
        "default_target": "main_text",
        "unit": "cm",
        "keywords": [
            "абзацный отступ",
            "отступ первой строки",
            "красная строка",
        ],
        "value_pattern": r"(\d+(?:[.,]\d+)?)\s*(см|мм)",
        "operator": "equals",
        "value_type": "length_cm",
    },
    {
        "parameter": "alignment",
        "default_target": "main_text",
        "unit": None,
        "keywords": ["выравнивание", "выравнивают", "выравнивать", "выравнивается", "выравненный"],
        "value_pattern": r"(по ширине|по центру|по левому(?: краю)?|слева|центрирован\w*)",
        "operator": "equals",
        "value_type": "mapped_string",
        "value_map": {
            "по ширине": "justify",
            "по центру": "center",
            "по левому": "left",
            "по левому краю": "left",
            "слева": "left",
        },
    },
    {
        "parameter": "page_format",
        "default_target": "page",
        "unit": None,
        "keywords": ["формат", "формата"],
        "value_pattern": r"(A4|А4|A5|А5)",
        "operator": "equals",
        "value_type": "mapped_string",
        "value_map": {
            "A4": "A4",
            "А4": "A4",
            "A5": "A5",
            "А5": "A5",
        },
    },
    {
        "parameter": "bold",
        "default_target": "heading",
        "unit": None,
        "keywords": ["полужирн", "жирн"],
        "value_pattern": r"(полужирн\w*|жирн\w*)",
        "operator": "equals",
        "value_type": "constant",
        "value": True,
    },
    {
        "parameter": "italic",
        "default_target": "main_text",
        "unit": None,
        "keywords": ["курсив"],
        "value_pattern": r"(курсив\w*)",
        "operator": "equals",
        "value_type": "constant",
        "value": True,
    },
]
